import AppKit
import BlobStore
import Foundation

/// Traduce el contenido del portapapeles del sistema al modelo de la app.
///
/// El orden en que se prueban los tipos importa: un archivo copiado en el
/// Finder también ofrece su ruta como texto, y una imagen copiada de una web
/// llega además como HTML. Se clasifica por el tipo más específico disponible y
/// se conservan todas las representaciones para el momento de pegar.
public enum PasteboardReader {
    /// Por encima de este tamaño la representación va a disco en vez de a la
    /// fila de la base de datos.
    public static let inlineByteLimit = 4 * 1024

    /// Compatibilidad para quien solo quiere el item.
    public static func read(
        from pasteboard: NSPasteboard = .general,
        sourceBundle: String? = nil,
        sourceName: String? = nil
    ) -> CapturedItem? {
        inspect(pasteboard, sourceBundle: sourceBundle, sourceName: sourceName).item
    }

    /// Lee el portapapeles y explica por qué, si no captura nada.
    public static func inspect(
        _ pasteboard: NSPasteboard = .general,
        sourceBundle: String? = nil,
        sourceName: String? = nil,
        limits: CaptureLimits = .standard
    ) -> CaptureOutcome {
        guard let items = pasteboard.pasteboardItems, let first = items.first else {
            return .ignored(.empty)
        }

        let types = Set(first.types.map(\.rawValue))

        // Contenido marcado por su origen como no historificable. Se comprueba
        // antes que nada: un gestor de contraseñas que marca su portapapeles
        // confía en que nadie lo guarde, y la lista manual de exclusiones
        // siempre va por detrás de las apps que el usuario instala.
        //
        // `AutoGeneratedType` marca lo que ha escrito una herramienta y no una
        // acción directa de la persona — típicamente, otro gestor de
        // portapapeles al pegar. Ignorarlo evita que dos gestores activos a la
        // vez se reciclen contenido mutuamente y llenen ambos historiales de
        // ecos del otro.
        let ignored = [UTIs.concealed, UTIs.transient, UTIs.autoGenerated]
        if ignored.contains(where: types.contains) {
            return .ignored(.markedPrivate)
        }

        if let captured = readFiles(items, sourceBundle: sourceBundle, sourceName: sourceName) {
            return .captured(captured)
        }

        switch readImage(first, sourceBundle: sourceBundle, sourceName: sourceName, limits: limits) {
        case .captured(let item): return .captured(item)
        case .ignored(.tooLarge(let bytes, let limit)):
            return .ignored(.tooLarge(bytes: bytes, limit: limit))
        case .ignored: break
        }

        if let captured = readColor(pasteboard, sourceBundle: sourceBundle, sourceName: sourceName) {
            return .captured(captured)
        }
        return readText(first, sourceBundle: sourceBundle, sourceName: sourceName, limits: limits)
    }

    // MARK: - Archivos

    private static func readFiles(
        _ items: [NSPasteboardItem],
        sourceBundle: String?,
        sourceName: String?
    ) -> CapturedItem? {
        let urls: [URL] = items.compactMap { item in
            guard let string = item.string(forType: .fileURL) else { return nil }
            return URL(string: string)
        }
        guard !urls.isEmpty else { return nil }

        let names = urls.map { $0.lastPathComponent }
        let paths = urls.map { $0.path(percentEncoded: false) }

        let representations = urls.compactMap { url -> Representation? in
            guard let data = url.absoluteString.data(using: .utf8) else { return nil }
            return Representation(uti: UTIs.fileURL, blobHash: nil, inline: data, bytes: data.count)
        }

        return CapturedItem(
            kind: .file,
            representations: representations,
            preview: names.joined(separator: ", "),
            // Se indexan también las rutas: buscar por carpeta es tan natural
            // como buscar por nombre de archivo.
            searchableText: (names + paths).joined(separator: "\n"),
            sourceBundle: sourceBundle,
            sourceName: sourceName,
            concealed: false,
            imageData: nil,
            fingerprint: fingerprint(of: paths.joined(separator: "\u{1}"))
        )
    }

    // MARK: - Imágenes

    private static func readImage(
        _ item: NSPasteboardItem,
        sourceBundle: String?,
        sourceName: String?,
        limits: CaptureLimits
    ) -> CaptureOutcome {
        // PNG primero: TIFF es lo que ofrece el sistema por defecto y pesa
        // varias veces más para el mismo contenido.
        let payload: (data: Data, uti: String)? = {
            if let data = item.data(forType: .png) { return (data, UTIs.png) }
            if let data = item.data(forType: .tiff) { return (data, UTIs.tiff) }
            return nil
        }()

        guard let payload, !payload.data.isEmpty else { return .ignored(.empty) }

        guard payload.data.count <= limits.maximumImageBytes else {
            return .ignored(.tooLarge(bytes: payload.data.count, limit: limits.maximumImageBytes))
        }

        // El recuento de píxeles se lee de la cabecera, sin decodificar. Es la
        // comprobación que de verdad protege: un PNG muy comprimido puede pesar
        // poco y ocupar gigabytes al descomprimirse, a cuatro bytes por píxel.
        if let size = BlobStore.imageSize(of: payload.data) {
            let pixels = size.width * size.height
            if pixels > limits.maximumImagePixels {
                return .ignored(.tooLarge(bytes: pixels * 4, limit: limits.maximumImagePixels * 4))
            }
        }

        return .captured(CapturedItem(
            kind: .image,
            representations: [
                Representation(uti: payload.uti, blobHash: nil, inline: nil, bytes: payload.data.count)
            ],
            preview: "",
            searchableText: nil,  // Lo rellena el reconocimiento de texto.
            sourceBundle: sourceBundle,
            sourceName: sourceName,
            concealed: false,
            imageData: payload.data,
            fingerprint: BlobStore.hash(of: payload.data)
        ))
    }

    // MARK: - Color

    private static func readColor(
        _ pasteboard: NSPasteboard,
        sourceBundle: String?,
        sourceName: String?
    ) -> CapturedItem? {
        guard let color = NSColor(from: pasteboard) else { return nil }
        let hex = color.hexString

        guard let data = hex.data(using: .utf8) else { return nil }
        return CapturedItem(
            kind: .color,
            representations: [
                Representation(uti: UTIs.plainText, blobHash: nil, inline: data, bytes: data.count)
            ],
            preview: hex,
            searchableText: hex,
            sourceBundle: sourceBundle,
            sourceName: sourceName,
            concealed: false,
            imageData: nil,
            fingerprint: fingerprint(of: "color:" + hex)
        )
    }

    // MARK: - Texto

    private static func readText(
        _ item: NSPasteboardItem,
        sourceBundle: String?,
        sourceName: String?,
        limits: CaptureLimits
    ) -> CaptureOutcome {
        guard let plain = item.string(forType: .string), !plain.isEmpty else {
            return .ignored(.empty)
        }
        guard !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .ignored(.empty)
        }

        // El techo se mide en bytes UTF-8, no en caracteres: es lo que se va a
        // escribir en disco y lo que ocupa en memoria. Un texto de emoji pesa
        // cuatro veces más que uno latino con el mismo número de caracteres.
        let byteCount = plain.utf8.count
        guard byteCount <= limits.maximumTextBytes else {
            return .ignored(.tooLarge(bytes: byteCount, limit: limits.maximumTextBytes))
        }

        var representations: [Representation] = []
        var kind: ItemKind = .text

        // Se guardan todas las variantes que ofrezca el origen. Sin esto,
        // pegar en un editor con formato perdería estilos que el usuario sí
        // había copiado.
        if let rtf = item.data(forType: .rtf) {
            representations.append(makeRepresentation(uti: UTIs.rtf, data: rtf))
            kind = .richText
        }
        if let html = item.data(forType: .html) {
            representations.append(makeRepresentation(uti: UTIs.html, data: html))
            kind = .richText
        }

        if let plainData = plain.data(using: .utf8) {
            representations.append(makeRepresentation(uti: UTIs.plainText, data: plainData))
        }

        if isLikelyURL(plain) { kind = .url }

        return .captured(CapturedItem(
            kind: kind,
            representations: representations,
            preview: singleLinePreview(plain),
            searchableText: plain,
            sourceBundle: sourceBundle,
            sourceName: sourceName,
            concealed: false,
            imageData: nil,
            fingerprint: fingerprint(of: plain)
        ))
    }

    // MARK: - Apoyo

    private static func makeRepresentation(uti: String, data: Data) -> Representation {
        if data.count <= inlineByteLimit {
            return Representation(uti: uti, blobHash: nil, inline: data, bytes: data.count)
        }
        // El hash se calcula aquí y el volcado a disco lo hace el ingestor: el
        // lector no debe tocar el sistema de ficheros.
        return Representation(
            uti: uti,
            blobHash: BlobStore.hash(of: data),
            inline: data,  // Transitorio: el ingestor lo mueve al almacén.
            bytes: data.count
        )
    }

    static func isLikelyURL(_ string: String) -> Bool {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.contains(" "), trimmed.count > 6, trimmed.count < 2048 else { return false }
        guard let url = URL(string: trimmed), let scheme = url.scheme?.lowercased() else { return false }
        return ["http", "https", "ftp", "mailto", "file"].contains(scheme) && url.host != nil
            || scheme == "mailto"
    }

    static func singleLinePreview(_ text: String, limit: Int = 300) -> String {
        let collapsed = text
            .replacingOccurrences(of: "\r\n", with: " ")
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\t", with: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)

        // Se colapsan los espacios repetidos para que el preview no quede lleno
        // de huecos al venir de código indentado.
        let squeezed = collapsed.split(separator: " ", omittingEmptySubsequences: true).joined(separator: " ")
        return squeezed.count <= limit ? squeezed : String(squeezed.prefix(limit)) + "…"
    }

    private static func fingerprint(of string: String) -> String {
        BlobStore.hash(of: Data(string.utf8))
    }
}

extension NSColor {
    var hexString: String {
        guard let rgb = usingColorSpace(.sRGB) else { return "#000000" }
        let red = Int((rgb.redComponent * 255).rounded())
        let green = Int((rgb.greenComponent * 255).rounded())
        let blue = Int((rgb.blueComponent * 255).rounded())
        return String(format: "#%02X%02X%02X", red, green, blue)
    }
}
